apiVersion: v1
kind: Pod
metadata:
	name: votinng-app-pod
	labels:
		name: voting-app-pod
		app: demo-voting-pod
spec:
	containers:
		- name: voting-app-pod
		  image: dockersamples/examplevotingapp_vote
		  ports:
			- containerPort: 80
			